sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
before script:
  - yarn bootstrap
script:
  - yarn build && yarn test
