sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
before_install:
  - yarn bootstrap
before script:
  - yarn build
script:
  - yarn test
